FROM php:8.3-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql

#need composer here

# allow super user - need to allow this if we use composer at all times.

ENV COMPOSER_ALLOW_SUPERUSER=1

#obtain composer using multi-staged build

COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer

# here we are copying only composer.json and composer.lock ( instead of copying enteire source)
# right before doing composer install
# This is enough to to take advantage of docker cache and composer install will
# be executed only when composer.json/lock have changed

COPY ../../composer.* ./

#install

RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-interaction

# copy application and files to the working directory

COPY ./app .


# run composer dump autoload --optimize

RUN composer dump-autoload --optimize


